version: "3"

services: 
  api:
    build: api
    ports:
      - "8080:8080"
    env_file:
      - ./api/.env
    depends_on:
      - db
  db: 
    build: db
    ports:
     - "6379:6379"
    volumes:
    - .data:/data